### ISSUE TITLE
No reverse lookup zones created.

### ISSUE THREAD

**Issue by ElApe** [gitbls/ndm#2]
Awesome project, thank you,

I have just installed and setup a complete new zone with it and it all appears to work fine apart from the lack of reverse lookup zones.

Is this correct of did I fluff something?

**Comment by gitbls** [comment]
Hi, glad you like it, even though you're having a problem ;).

Why do you think the reverse lookup zones aren't being created? Please include an 'ls -lt' directory listing from /etc/bind (or wherever the bind DB is on your system). There should be a file there named 'db.nnn.nnn.nnn' (with the nnn's being the first 3 octets of your LAN IP range). 

Also, please include the output from the bash command: 'nslookup some.valid.ip.address' on your LAN.

On mine, I get 
```
pisrv1/etc/bind# nslookup 192.168.92.5
5.92.168.192.in-addr.arpa       name = pvn.mydomain.com.
```
Thanks!

**Comment by ElApe** [comment]
Hi there, thanks for the reply.

I have a db.192.168.1.16 file but it is empty.
more db.192.168.1.16
; 2021031501 1.168.192.in-addr.arpa created Mon Mar 15 19:27:29 2021
$TTL    86400    ; 24 hours. could have been written as 24h or 1d
$ORIGIN 1.168.192.in-addr.arpa.
1.168.192.in-addr.arpa.  IN    SOA sshtest. root.ussharps.co.uk. (
                     2021031501 ; serial
                     28800      ; refresh 8H
                     7200       ; retry   2H
                     604800     ; expire  1W
                     86400      ; minimum 1D
                     )
       IN NS      sshtest.ussharps.co.uk.
       IN MX      10 postoffice.ussharps.co.uk.

$GENERATE 150-200 $ CNAME $.1.168.192.dhcp.


root@sshtest:/etc/bind$ nslookup 192.168.1.16
** server can't find 16.1.168.192.in-addr.arpa: NXDOMAIN

This is just a test server I'm playing with at the moment, have been tinkering with 4, yes 4, factor authentication for my public facing SSH server ;)

**Comment by gitbls** [comment]
What does 'sudo ndm config' say for the 'subnet' configuration item? It should be 192.168.1 in your case. If that's not set, then the reverse lookup zone won't be created. 

If that's correct, would you be willing to email me your /etc/dbndm.json file? There are some per-host settings that would prevent entries from being output (hostonly, zoneonly, and dhcponly).

My email is on the page https://github.com/gitbls (LH column).

**Comment by ElApe** [comment]
Ahaaa, there it is, I must of put the servers IP address in for the subnet, new I had fluffed it 

You can always rely on a user to cock it all up in ways you would never of thought possibe ;)

Thanks for getting back to me so quickly.

**Comment by ElApe** [comment]
PEBKAC, all sorted.

**Comment by gitbls** [comment]
Great that it was an easy one!

If you run into any other issues, or have any feedback (besides "why aren't you checking the subnet config item for correctness? ;) ) please let me know.

And, good luck with your 4FA!
