### ISSUE TITLE
can not 'ndm' build

### ISSUE THREAD

**Issue by peritonow** [gitbls/ndm#3]
I am trying to run

$ sudo ndm build

but getting eror: "? Error loading file ndmdnsbind for DNS"

**Comment by gitbls** [comment]
Hi, sorry that you're having a problem. Sounds like you didn't get the 3 additional Python files needed for ndm. The EZndmInstaller does this by default (or at least it's supposed to :))

How did you install ndm? 

If you downloaded ndm without using EZndmInstaller, you need to get the 3 additional files: ndmdhcpisc.py, ndmdnsbind.py, and ndmdnsmasq.py into the exact same directory as ndm. And, while ndm doesn't have the ".py" extension, Python seems to require that the 3 additional files MUST have the ".py" extension for the dynamic load to work.

If you believe that you have it set up correctly, please provide the following outputs:
```
ls -l `which ndm`
ls -l $(dirname `which ndm`)/ndm*.py
```

**Comment by peritonow** [comment]
Hi,

I did use EZndmInstaller and I got all the files as listed in git and they
are ‘rwx’ with py extension. The ndm is installed under /usr/local/bin on
newest Ubuntu running on raspberry pi. I am currently traveling and will be
able to provide output on Tuesday. I think it is also newest python3.

Thank you,
John Wagner

**Comment by gitbls** [comment]
Ubuntu is a HUGE hint! I did mention way down at the bottom of the README that Ubuntu hadn't been tested.

Indeed...it doesn't work. I'm fixing that, then will go through the test cycle. There will be a new version to try by the time you get back to this. Stay tuned.

**Comment by gitbls** [comment]
V2.2 is posted, and works on Ubuntu. Let me know how it goes for you when you have an opportunity to try it.

**Comment by peritonow** [comment]
Hi, 

Here is the output of the commands:
ubuntu@beta:~$ ls -l `which ndm`
-rwxr-xr-x 1 root root 38799 Apr 30 17:17 /usr/local/bin/ndm
ubuntu@beta:~$ ls -l $(dirname `which ndm`)/ndm*.py
-rwxr-xr-x 1 root root  7707 Apr 30 17:17 /usr/local/bin/ndmdhcpisc.py
-rwxr-xr-x 1 root root   782 Apr 30 17:17 /usr/local/bin/ndmdhcpnone.py
-rwxr-xr-x 1 root root 18446 Apr 30 17:17 /usr/local/bin/ndmdnsbind.py
-rwxr-xr-x 1 root root  9681 Apr 30 17:17 /usr/local/bin/ndmdnsmasq.py

I will test the new version.

**Comment by peritonow** [comment]
Thank you... all is working.

**Comment by gitbls** [comment]
Thanks for letting me know. Enjoy!
