### ISSUE TITLE
DNS zone generated file

### ISSUE THREAD

**Issue by peritonow** [gitbls/ndm#5]
The generated zone files for my local network includes a last line
**$GENERATE 10-129 $ CNAME $.72.168.192.dhcp.**
which is causing a problem 

```
May 11 15:55:40 beta named[10168]: dns_master_load: /etc/bind/db.192.168.72:59: 10.72.168.192.in-addr.arpa: CNAME and other data
May 11 15:55:40 beta named[10168]: $GENERATE: /etc/bind/db.192.168.72:59: CNAME and other data
May 11 15:55:40 beta named[10168]: zone 72.168.192.in-addr.arpa/IN: loading from master file /etc/bind/db.192.168.72 failed: CNAME>
May 11 15:55:40 beta named[10168]: zone 72.168.192.in-addr.arpa/IN: not loaded due to errors.
```
after removing the last line:
**$GENERATE 10-129 $ CNAME $.72.168.192.dhcp.**
and restarting bind service
$ sudo systemctl restart bind9
$ sudo systemctl status bind9
I am getting no errors from bind9 status command:
May 11 16:03:46 beta named[10245]: zone 72.168.192.dhcp/IN: loaded serial 2021051102
May 11 16:03:46 beta named[10245]: zone localhost/IN: loaded serial 2
May 11 16:03:46 beta named[10245]: all zones loaded
May 11 16:03:46 beta named[10245]: running

**Comment by peritonow** [comment]
I am enjoying this tools tremendously and it have saved me a lot of time from maintaining the dhcp and bind manually as I was doing it still recently. Thank you.

**Comment by peritonow** [comment]
I am not familiar with $GENERATE and I don't remember using it. The workaround is working just fine..  I am not using any CNAMEs in zone files, only A records.

**Comment by gitbls** [comment]
I'm still confused as to why you're seeing this error, and would like to see your ndm config as I suggested above. Thx
