### ISSUE TITLE
lower() not found

### ISSUE THREAD

**Issue by peritonow** [gitbls/ndm#6]
root@ubuntu:~# sudo ndm config --domain xxxxxxxxxx.org
Traceback (most recent call last):
  File "/usr/local/bin/ndm", line 826, in <module>
    pd.args.func(pd)
  File "/usr/local/bin/ndm", line 453, in cmd_config
    doconfigitem(pd, 'domain', pd.args.domain, lowerit=True)
  File "/usr/local/bin/ndm", line 447, in doconfigitem
    pd.db['cfg'][dest] = argval if lower == False else argval.lower()
NameError: name 'lower' is not defined

**Comment by peritonow** [comment]
is:
    if argval != None:
        pd.db['cfg'][dest] = argval if lower == False else argval.lower()
        pd.dbmodified = True
probable fix:
    if argval != None:
        pd.db['cfg'][dest] = argval if lowerit == False else argval.lower()
        pd.dbmodified = True

instead of 'lower' there should be 'lowerit' instead

**Comment by gitbls** [comment]
Urgh! Thanks for finding. Changed the variable name and incompletely implemented the change. Fixed in v2.6.
