### ISSUE TITLE
'can't clone pool group error': Ubuntu isc-dhcp-server V4.4.1-2.2ubuntu6.1

### ISSUE THREAD

**Issue by peritonow** [gitbls/ndm#7]
I have recently upgraded to ubuntu 21.04 with DHCP Server 4.4.1 and after getting all build with ndm I am getting the error from dhcp:

May 31 14:47:15 gamma sudo[3132]: pam_unix(sudo:session): session closed for user root
May 31 14:47:15 gamma dhcpd[3135]: Internet Systems Consortium DHCP Server 4.4.1
May 31 14:47:15 gamma sh[3135]: Internet Systems Consortium DHCP Server 4.4.1
May 31 14:47:15 gamma sh[3135]: Copyright 2004-2018 Internet Systems Consortium.
May 31 14:47:15 gamma sh[3135]: All rights reserved.
May 31 14:47:15 gamma sh[3135]: For info, please visit https://www.isc.org/software/dhcp/
May 31 14:47:15 gamma dhcpd[3135]: Copyright 2004-2018 Internet Systems Consortium.
May 31 14:47:15 gamma dhcpd[3135]: All rights reserved.
May 31 14:47:15 gamma dhcpd[3135]: For info, please visit https://www.isc.org/software/dhcp/
May 31 14:47:15 gamma sudo[3138]:     root : TTY=pts/0 ; PWD=/etc/dhcp ; USER=root ; COMMAND=/usr/bin/systemctl status isc-dhcp-server
May 31 14:47:15 gamma dhcpd[3135]: can't clone pool group.
May 31 14:47:15 gamma sh[3135]: can't clone pool group.
May 31 14:47:15 gamma sh[3135]: If you think you have received this message due to a bug rather
May 31 14:47:15 gamma sh[3135]: than a configuration issue please read the section on submitting
May 31 14:47:15 gamma sh[3135]: bugs on either our web page at www.isc.org or in the README file
May 31 14:47:15 gamma sh[3135]: before submitting a bug.  These pages explain the proper
May 31 14:47:15 gamma sh[3135]: process and the information we find helpful for debugging.
May 31 14:47:15 gamma sh[3135]: exiting.
May 31 14:47:15 gamma dhcpd[3135]:
May 31 14:47:15 gamma dhcpd[3135]: If you think you have received this message due to a bug rather
May 31 14:47:15 gamma systemd[1]: isc-dhcp-server.service: Main process exited, code=exited, status=1/FAILURE

not quite sure what `can't clone pool group` is about...

**Comment by peritonow** [comment]
it's totally weird since ndm create subnet with pool in it:
subnet 192.168.72.0 netmask 255.255.255.0 {
    option domain-search "lg.org", "dyn.lg.org";
    option broadcast-address 192.168.72.255;
    allow duplicates;
    ddns-updates off;
    pool {
        ddns-updates on;
        allow unknown-clients;
        option domain-name "dyn.lg.org";
        ddns-rev-domainname "dhcp";
        default-lease-time 86400;
        max-lease-time 86400;
        range 192.168.72.10 192.168.72.129;
    }
by removing pool statement I get:
subnet 192.168.72.0 netmask 255.255.255.0 {
    option domain-search "lg.org", "dyn.lg.org";
    option broadcast-address 192.168.72.255;
    allow duplicates;
    ddns-updates off;
        ddns-updates on;
        allow unknown-clients;
        option domain-name "dyn.lg.org";
        ddns-rev-domainname "dhcp";
        default-lease-time 86400;
        max-lease-time 86400;
        range 192.168.72.10 192.168.72.129;
}

and isc-dhcp-server.service starts without problem.

**Comment by gitbls** [comment]
My ubuntu system had isc-dhcp-server V4.4.1-2.2-ubuntu6 installed and the service started correctly. I updated to isc-dhcp-server V4.4.1-2.2ubuntu6.1 and it's failing with the error you're seeing. 

At least on Ubuntu 21.04, if the pool declaration is pulled to outside the subnet declaration, everything works. Need to test on RasPiOS as well, will update here once the proper fix is sorted.

**Comment by gitbls** [comment]
I joined the isc-dhcp-server mailing list and submitted a post to it, but it hasn't been posted yet.

[Here's](https://ubuntuforums.org/showthread.php?t=2462984) a similar post that I made to the Ubuntu forum.

**Comment by peritonow** [comment]
That's interesting since it shows isc-dhcp-server version V4.4.1-2.2 in both version of ubuntu6 and ubuntu6.1. So, it seems that probably ubuntu put a development branch into production with existing production version of isc-dhcp-server. As far as I know no changes between minor versions not suppose to 'break' the software compatibility. I wonder which version did they push... :)  Good question for developers of isc-dhcp-server. Thank you.

**Comment by gitbls** [comment]
Unfortunately, the post to the isc-dhcp-server mailing list seems to just go into a black hole (doesn't get posted to the list). I'm thinking that they looked at my mail and said "It's a ubuntu problem" and zapped it.

There are now 2 and possibly 3 posts in the Ubuntu forums about this issue. The 3rd person didn't provide any information on the error he's seeing, and hasn't been back to respond to my question to get more info on his issue.

I'm going to leave this open for tracking, but this is a Ubuntu issue and can only be fixed by them. I hope they get to it soon. 

One of the joys of living on the bleeding edge!

**Comment by gitbls** [comment]
A reply from the isc-dhcp-server mailing list indicates that the subnet and pool config is correct as is. I just filed a bug in Ubuntu Launchpad against this.

**Comment by gitbls** [comment]
Response on Launchpad to the bug report:
I can confirm the update introduced a regression on Hirsute (and Impish I presume). Focal and Groovy work properly. Unfortunately, it's not related to the security patch, but it stems from the package being rebuilt with the newer toolchain in Hirsute, so removing the patch won't fix the issue.

I am currently investigating how to fix this.

** Also affects: isc-dhcp (Ubuntu Hirsute)
   Importance: Undecided
       Status: New

** Also affects: isc-dhcp (Ubuntu Impish)
   Importance: Undecided
       Status: Confirmed

** Changed in: isc-dhcp (Ubuntu Hirsute)
       Status: New => Confirmed

** Changed in: isc-dhcp (Ubuntu Hirsute)
     Assignee: (unassigned) => Marc Deslauriers (mdeslaur)

** Changed in: isc-dhcp (Ubuntu Impish)
     Assignee: (unassigned) => Marc Deslauriers (mdeslaur)

** Changed in: isc-dhcp (Ubuntu Hirsute)
   Importance: Undecided => Critical

** Changed in: isc-dhcp (Ubuntu Impish)
   Importance: Undecided => Critical

**Comment by gitbls** [comment]
Latest launchpad update: This bug was fixed in the package isc-dhcp - 4.4.1-2.2ubuntu6.2
---------------
isc-dhcp (4.4.1-2.2ubuntu6.2) hirsute-security; urgency=medium

  * Fix regression caused by rebuild with newer toolchain (LP: #1930917)
    - debian/rules: build with -fno-strict-aliasing.

 -- Marc Deslauriers <marc.deslauriers@ubuntu.com>  Mon, 07 Jun 2021
08:08:56 -0400

** Changed in: isc-dhcp (Ubuntu Hirsute)
       Status: Confirmed => Fix Released

**Comment by gitbls** [comment]
Confirmed that isc-dhcp - 4.4.1-2.2ubuntu6.2 reverts the erroneous toolchain-induced change. @peritonow Please close this issue after you've verified it for yourself. Thx

**Comment by peritonow** [comment]
Yes, the problem is gone as well as $GENERATE statement works as expected - no more error messages
