### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by peritonow** [gitbls/ndm#9]
This is just something that is nice to have. On my home network I have a rogue device that I have no idea what it is and just by looking at MAC OID (https://www.wireshark.org/tools/oui-lookup.html) does not give me much information. So, I had to create a a deny by MAC configuration ( still testing )

I did following by adding:
```
class "ignore" {
    match pick-first-value (option dhcp-client-identifier,hardware);
    match if (binary-to-ascii (16,8,":",substring(hardware,0,7)) = "1:0:8:22:12:24:5a")
    log(info, (binary-to-ascii (16,8,":",substring(hardware, 0, 7))));
}
subclass "ignore" 1:0:8:22:12:24:5a;
```
and within pool in subnet section added statement:
`deny members of "ignore";`

I have used following website to come up with this configuration:
https://mwl.io/archives/962
https://kb.isc.org/docs/isc-dhcp-44-manual-pages-dhcp-eval
https://kb.isc.org/docs/isc-dhcp-41-manual-pages-dhcpdconf#subclasses

**Comment by gitbls** [comment]
I think this is a good idea. Would the following work for you? (names probably not what they'll actually be!)

- --dhcpheadinclude file - Would include the contents of the specified file in the first section of dhcpd.conf, before/after ddns-hostname
- --poolinclude file - Would include the contents of the specified file in the pool section

**Comment by peritonow** [comment]
`--poolinclude file` might be a better choice as it reference the immediate location of the rule.

**Comment by peritonow** [comment]
By the way, in 'Nameserver Failover' you might want mention keepalived package. The only difference is do not use label statements in virtual_ipaddress, bind should listen on port 53 on 'any' interface and one runs separate ndm with different pool allocation.  The somewhat good explanation is provided by link : http://woshub.com/keepalived-high-availability-with-ip-failover/#h2_1 . I am using pi-hole for the statistic and to block (blacklist) domains, but the forwarders are ndm managed bind/isc-dhcp.

**Comment by gitbls** [comment]
> `--poolinclude file` might be a better choice as it references the immediate location of the rule.

I think you need both, which was why I suggested two new switches. The first one adds the definition (your class "ignore") into the header part of the config file, and poolinclude adds the text to the pool section.

If there's only one switch, how would you get the ignore class into the header?

**Comment by gitbls** [comment]
> By the way, in 'Nameserver Failover' you might want mention keepalived package. The only difference is do not use `label` statements in virtual_ipaddress, bind should listen on port 53 on 'any' interface and one runs separate ndm with different pool allocation on each server(raspi). The somewhat good explanation is provided by link : http://woshub.com/keepalived-high-availability-with-ip-failover/#h2_1 . I am using pi-hole for the statistic and to block (blacklist) domains, but the forwarders are ndm managed bind/isc-dhcp.
> 
> Thanks for the notes on systemd-networkd... being new on ubuntu it would take me some time to learn cloud-init which would have been a total waste of time. Your notes on systemd-networkd helped a lot and cloud-init was removed.

Thanks! I'll look into keepalived after I finish a round of updates for my apps on Debian Bullseye. And, glad to hear that the systemd-networkd notes were helpful.  👍

**Comment by peritonow** [comment]
regarding the new feature - I was more thinking about doing it per feature addition instead of configuration naming convention (which I am not that much familiar with). But either way would work...

**Comment by gitbls** [comment]
It's much easier to add a configuration naming convention than per-feature additions. Doing a generalized solution keeps me out of a stream of "Please add this new capability" requests. I'll get the generalized solution done when I do Bullseye testing on ndm.

**Comment by gitbls** [comment]
OK, here's what I'm going to implement for the feature request: --dhcpglobalinclude will add the lines of text in the specified file to the end of the global section in dhcpd.conf following the ddns-hostname statement. --dhcppoolinclude will add the lines from the specified file to the pool section following the range statement.

You'll create 2 files, one for each, and put the "class ignore" statement in the globalinclude file, and the "deny members" statement in the poolinclude file.

This will do what you want, as I understand the ask. Does this work for you?

**Comment by gitbls** [comment]
Checked in.
